# Generated by Django 6.0.5 on 2026-05-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='current', max_length=50, unique=True)),
                ('logo_name', models.CharField(default='logo.png', max_length=100)),
                ('logo_data', models.BinaryField(blank=True, null=True)),
                ('logo_mimetype', models.CharField(default='image/png', max_length=50)),
                ('background_name', models.CharField(default='background.png', max_length=100)),
                ('background_data', models.BinaryField(blank=True, null=True)),
                ('background_mimetype', models.CharField(default='image/png', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Branding',
                'verbose_name_plural': 'System Branding',
            },
        ),
    ]
