# Generated by Django 6.0.5 on 2026-05-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_login_attempts_user_login_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('operator', 'Operator'), ('viewer', 'Viewer'), ('supreme_admin', 'Supreme Admin'), ('ultra_admin', 'Ultra Admin')], default='operator', max_length=20),
        ),
    ]
