# Generated by Django 6.0.5 on 2026-05-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemaster',
            name='basin_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
