# Generated by Django 6.0.5 on 2026-05-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_master', '0002_sitemaster_basin_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitemaster',
            name='basin_name',
        ),
        migrations.RemoveField(
            model_name='sitemaster',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sitemaster',
            name='dam_reservoir_name',
        ),
        migrations.RemoveField(
            model_name='sitemaster',
            name='danger_level',
        ),
        migrations.RemoveField(
            model_name='sitemaster',
            name='district_name',
        ),
        migrations.RemoveField(
            model_name='sitemaster',
            name='gauge_details',
        ),
        migrations.RemoveField(
            model_name='sitemaster',
            name='gauge_type',
        ),
        migrations.RemoveField(
            model_name='sitemaster',
            name='minimum_draw_down_level',
        ),
        migrations.RemoveField(
            model_name='sitemaster',
            name='river_name',
        ),
        migrations.RemoveField(
            model_name='sitemaster',
            name='site_name',
        ),
        migrations.RemoveField(
            model_name='sitemaster',
            name='state_name',
        ),
        migrations.RemoveField(
            model_name='sitemaster',
            name='warning_level',
        ),
        migrations.AddField(
            model_name='sitemaster',
            name='basin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitemaster',
            name='catchment_area_sqkm',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sitemaster',
            name='dam_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitemaster',
            name='dead_storage_level',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='sitemaster',
            name='division',
            field=models.CharField(default='GENERAL', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitemaster',
            name='functional',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitemaster',
            name='instrumentation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitemaster',
            name='live_capacity_mcm',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sitemaster',
            name='max_water_level',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='sitemaster',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='sitemaster',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemaster',
            name='state',
            field=models.CharField(default='Himachal Pradesh', max_length=100),
        ),
        migrations.AddField(
            model_name='sitemaster',
            name='station_id_device',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sitemaster',
            name='station_name',
            field=models.CharField(default='STATION', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitemaster',
            name='total_capacity_mcm',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sitemaster',
            name='transmission_minutes',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitemaster',
            name='full_reservoir_level',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='sitemaster',
            name='site_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='sitemaster',
            name='site_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=30),
        ),
    ]
