# Generated by Django 6.0.5 on 2026-05-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_master', '0003_remove_sitemaster_basin_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemaster',
            name='danger_level',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='sitemaster',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitemaster',
            name='minimum_draw_down_level',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='sitemaster',
            name='river_tributary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitemaster',
            name='warning_level',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='sitemaster',
            name='division',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitemaster',
            name='instrumentation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
