# Generated by Django 6.0.5 on 2026-05-15 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites_master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('observation_id', models.AutoField(primary_key=True, serialize=False)),
                ('observation_date', models.DateField()),
                ('observation_time', models.TimeField()),
                ('current_water_level', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_inflow', models.DecimalField(decimal_places=3, max_digits=12)),
                ('total_outflow', models.DecimalField(decimal_places=3, max_digits=12)),
                ('live_storage', models.DecimalField(decimal_places=3, max_digits=12)),
                ('dead_storage', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('percentage_full', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rainfall_today', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cumulative_rainfall', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gates_open', models.BooleanField(default=False)),
                ('number_of_gates_open', models.IntegerField(blank=True, null=True)),
                ('gate_opening_height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discharge_through_gates', models.DecimalField(decimal_places=3, max_digits=12)),
                ('spillway_discharge', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('weather_condition', models.CharField(choices=[('Clear', 'Clear'), ('Cloudy', 'Cloudy'), ('Rainy', 'Rainy'), ('Foggy', 'Foggy'), ('Stormy', 'Stormy')], max_length=50)),
                ('water_quality', models.CharField(choices=[('Good', 'Good'), ('Turbid', 'Turbid'), ('Discolored', 'Discolored'), ('Flood Water', 'Flood Water')], max_length=50)),
                ('site_condition_remarks', models.TextField(blank=True, max_length=500, null=True)),
                ('general_remarks', models.TextField(blank=True, max_length=500, null=True)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('FINAL', 'FINAL')], default='DRAFT', max_length=10)),
                ('final_submission_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='sites_master.sitemaster')),
            ],
            options={
                'verbose_name': 'Observation',
                'verbose_name_plural': 'Observations',
                'db_table': 'observations',
                'ordering': ['-observation_date', '-observation_time'],
            },
        ),
    ]
