# Generated by Django 6.0.5 on 2026-05-15 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationPhoto',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='observation_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='observations.observation')),
            ],
            options={
                'verbose_name': 'Observation Photo',
                'verbose_name_plural': 'Observation Photos',
                'db_table': 'observation_photos',
            },
        ),
    ]
