# Generated by Django 6.0.5 on 2026-05-16 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_observationphoto'),
        ('sites_master', '0003_remove_sitemaster_basin_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observationphoto',
            name='observation',
        ),
        migrations.CreateModel(
            name='WaterLevelLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('observation_date', models.DateField()),
                ('observation_time', models.TimeField()),
                ('observation_datetime', models.DateTimeField(db_index=True)),
                ('water_level_m', models.DecimalField(decimal_places=3, max_digits=8)),
                ('storage_mcm', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('storage_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('inflow_cusecs', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('outflow_cusecs', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('net_change_m', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('observation_type', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('estimated', 'Estimated')], default='manual', max_length=20)),
                ('weather_condition', models.CharField(blank=True, max_length=50, null=True)),
                ('visibility', models.CharField(blank=True, max_length=30, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('entry_source', models.CharField(choices=[('mobile', 'Mobile App'), ('desktop', 'Web Dashboard'), ('api', 'External API')], default='mobile', max_length=20)),
                ('entry_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('entry_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_logs', to='sites_master.sitemaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_logs', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Water Level Log',
                'verbose_name_plural': 'Water Level Logs',
                'db_table': 'water_level_log',
                'unique_together': {('site', 'observation_datetime')},
            },
        ),
        migrations.CreateModel(
            name='DamObservation',
            fields=[
                ('obs_id', models.AutoField(primary_key=True, serialize=False)),
                ('spillway_gates_total', models.SmallIntegerField(blank=True, null=True)),
                ('spillway_gates_open', models.SmallIntegerField(blank=True, null=True)),
                ('spillway_opening_m', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('spillway_discharge_cusecs', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('sluice_gates_total', models.SmallIntegerField(blank=True, null=True)),
                ('sluice_gates_open', models.SmallIntegerField(blank=True, null=True)),
                ('sluice_discharge_cusecs', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('power_units_running', models.SmallIntegerField(blank=True, null=True)),
                ('power_generation_mw', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('power_discharge_cusecs', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('rainfall_today_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('rainfall_yesterday_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('rainfall_this_month_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('rainfall_this_year_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('upstream_level_m', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('downstream_level_m', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('tail_water_level_m', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('air_temp_celsius', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('water_temp_celsius', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('wind_speed_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('wind_direction', models.CharField(blank=True, max_length=10, null=True)),
                ('humidity_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('seepage_lt_per_min', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('piezometer_reading', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('dam_condition', models.CharField(default='Normal', max_length=30)),
                ('alert_level', models.CharField(default='Green', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dam_observations', to='sites_master.sitemaster')),
                ('log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dam_detail', to='observations.waterlevellog')),
            ],
            options={
                'verbose_name': 'Dam Observation',
                'verbose_name_plural': 'Dam Observations',
                'db_table': 'dam_observation',
            },
        ),
        migrations.AddField(
            model_name='observationphoto',
            name='log',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='observations.waterlevellog'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Observation',
        ),
    ]
