# Generated by Django 6.0.5 on 2026-05-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0003_remove_observationphoto_observation_waterlevellog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VwDashboardSummary',
            fields=[
                ('total_sites', models.BigIntegerField(primary_key=True, serialize=False)),
                ('total_operators', models.BigIntegerField(blank=True, null=True)),
                ('total_entries', models.BigIntegerField(blank=True, null=True)),
                ('pending_verifications', models.BigIntegerField(blank=True, null=True)),
                ('red_alert_sites', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vw_dashboard_summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwFullEntryDetails',
            fields=[
                ('log_id', models.IntegerField(primary_key=True, serialize=False)),
                ('observation_datetime', models.DateTimeField(blank=True, null=True)),
                ('site_id', models.IntegerField(blank=True, null=True)),
                ('station_name', models.CharField(blank=True, max_length=255, null=True)),
                ('site_code', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('water_level_m', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('storage_mcm', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('storage_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('inflow_cusecs', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('outflow_cusecs', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('spillway_gates_open', models.CharField(blank=True, max_length=255, null=True)),
                ('power_generation_mw', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('rainfall_today_mm', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('alert_level', models.CharField(blank=True, max_length=255, null=True)),
                ('is_verified', models.BooleanField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vw_full_entry_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwGisPopup',
            fields=[
                ('site_id', models.IntegerField(primary_key=True, serialize=False)),
                ('site_code', models.CharField(blank=True, max_length=255, null=True)),
                ('station_name', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('division', models.CharField(blank=True, max_length=255, null=True)),
                ('basin', models.CharField(blank=True, max_length=255, null=True)),
                ('dam_type', models.CharField(blank=True, max_length=255, null=True)),
                ('full_reservoir_level', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('water_level_m', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('storage_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('inflow_cusecs', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('outflow_cusecs', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('weather_condition', models.CharField(blank=True, max_length=255, null=True)),
                ('observation_datetime', models.DateTimeField(blank=True, null=True)),
                ('spillway_gates_open', models.CharField(blank=True, max_length=255, null=True)),
                ('spillway_discharge_cusecs', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('power_generation_mw', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('rainfall_today_mm', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('alert_level', models.CharField(blank=True, max_length=255, null=True)),
                ('dam_condition', models.CharField(blank=True, max_length=255, null=True)),
                ('operator_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'vw_gis_popup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwOperatorSite',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('site_id', models.IntegerField(blank=True, null=True)),
                ('site_code', models.CharField(blank=True, max_length=255, null=True)),
                ('station_name', models.CharField(blank=True, max_length=255, null=True)),
                ('division', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'vw_operator_site',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwSiteLatestStatus',
            fields=[
                ('site_id', models.IntegerField(primary_key=True, serialize=False)),
                ('site_code', models.CharField(blank=True, max_length=255, null=True)),
                ('station_name', models.CharField(blank=True, max_length=255, null=True)),
                ('division', models.CharField(blank=True, max_length=255, null=True)),
                ('basin', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('dam_type', models.CharField(blank=True, max_length=255, null=True)),
                ('site_status', models.CharField(blank=True, max_length=255, null=True)),
                ('log_id', models.IntegerField(blank=True, null=True)),
                ('observation_datetime', models.DateTimeField(blank=True, null=True)),
                ('water_level_m', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('water_level_ft', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('storage_mcm', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('storage_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('inflow_cusecs', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('outflow_cusecs', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('weather_condition', models.CharField(blank=True, max_length=255, null=True)),
                ('is_verified', models.BooleanField(blank=True, null=True)),
                ('operator_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'vw_site_latest_status',
                'managed': False,
            },
        ),
    ]
