# Generated by Django 6.0.5 on 2026-05-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0004_vwdashboardsummary_vwfullentrydetails_vwgispopup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterlevellog',
            name='observation_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterlevellog',
            name='water_level_m',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
    ]
