from django.db import connection
with connection.cursor() as cur:
    try:
        cur.execute('CREATE TABLE "user_master_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "usermaster_id" integer NOT NULL, "group_id" integer NOT NULL)')
    except: pass
    try:
        cur.execute('CREATE TABLE "user_master_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "usermaster_id" integer NOT NULL, "permission_id" integer NOT NULL)')
    except: pass
    try:
        cur.execute('ALTER TABLE "user_master_groups" ADD CONSTRAINT "user_master_groups_usermaster_id_group_id_080918ef_uniq" UNIQUE ("usermaster_id", "group_id")')
    except: pass
    try:
        cur.execute('ALTER TABLE "user_master_user_permissions" ADD CONSTRAINT "user_master_user_permiss_usermaster_id_permission_83907301_uniq" UNIQUE ("usermaster_id", "permission_id")')
    except: pass
    print("Missing tables/constraints checked/created.")
