# Generated by Django 6.0.5 on 2026-05-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMaster',
            fields=[
                ('site_id', models.AutoField(primary_key=True, serialize=False)),
                ('site_code', models.CharField(max_length=20, unique=True)),
                ('station_name', models.CharField(max_length=150)),
                ('station_id_device', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('division', models.CharField(max_length=100)),
                ('basin', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(default='Himachal Pradesh', max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('dam_type', models.CharField(blank=True, max_length=50, null=True)),
                ('full_reservoir_level', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('max_water_level', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('dead_storage_level', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('total_capacity_mcm', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('live_capacity_mcm', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('catchment_area_sqkm', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('instrumentation', models.CharField(blank=True, max_length=100, null=True)),
                ('site_status', models.CharField(default='Active', max_length=30)),
                ('transmission_minutes', models.SmallIntegerField(blank=True, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('functional', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Master',
                'verbose_name_plural': 'Site Masters',
                'db_table': 'site_master',
            },
        ),
    ]
