# Generated by Django 6.0.5 on 2026-05-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('audit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=150)),
                ('site_id', models.IntegerField(blank=True, null=True)),
                ('record_id', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
